// Generated by dia2code
#ifndef POSITION__H
#define POSITION__H

/// class Position - 
class Position {
  // Attributes
private:
  int X;
  int Y;
  // Operations
public:
  position ();
  int getX ();
  int getY ();
  int setX ();
  int setY ();
  // Setters and Getters
};

#endif
