// Generated by dia2code
#ifndef STATE__BUILDINGRESID__H
#define STATE__BUILDINGRESID__H


namespace state {

  enum BuildingResID {
    brume_building     = 1,
    food_building     = 2,
    science_building     = 3,
    production_building     = 4
  };

};

#endif
