// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


namespace state {
  class Building;
}


namespace state {

  /// class Building - 
  class Building {
    // Attributes
  protected:
    int price;
    int production;
    int buildingID;
    // Operations
  public:
    Building ();
    ~Building ();
    void buyBuilding ();
    int turnLeft ();
    void upgradeBuilding (Building building);
    // Setters and Getters
    int getPrice() const;
    void setPrice(int price);
    int getProduction() const;
    void setProduction(int production);
    int getBuildingID() const;
    void setBuildingID(int buildingID);
  };

};

#endif
