// Generated by dia2code
#ifndef STATE__BUILDING_DEF__H
#define STATE__BUILDING_DEF__H


namespace state {
  class Building;
}

#include "UpDefID.h"
#include "Building.h"

namespace state {

  /// class Building_def - 
  class Building_def : public state::Building {
    // Associations
    // Attributes
  private:
    int health;
    int attack_power;
    UpDefID upgrade;
    // Operations
  public:
    int get_attack ();
    int get_health ();
    // Setters and Getters
  };

};

#endif
