// Generated by dia2code
#ifndef STATE__BUILDING_RESSOURCES__H
#define STATE__BUILDING_RESSOURCES__H


namespace state {
  class Building;
}

#include "Ressources.h"
#include "UpResID.h"
#include "BuildingResID.h"
#include "Building.h"

namespace state {

  /// class Building_ressources - 
  class Building_ressources : public state::Building {
    // Associations
    // Attributes
  protected:
    Ressources prod_type;
    int prod_quantity;
    UpResID upgrade;
    BuildingResID bui_res_type;
    // Setters and Getters
    Ressources getProd_type() const;
    void setProd_type(Ressources prod_type);
    int getProd_quantity() const;
    void setProd_quantity(int prod_quantity);
    UpResID getUpgrade() const;
    void setUpgrade(UpResID upgrade);
    BuildingResID getBui_res_type() const;
    void setBui_res_type(BuildingResID bui_res_type);
  };

};

#endif
