// Generated by dia2code
#ifndef STATE__MAP__H
#define STATE__MAP__H

#include <vector>

namespace state {
  class SpaceCell;
  class StellarWay;
}

#include "SpaceCell.h"
#include "StellarWay.h"

namespace state {

  /// class Map - 
  class Map {
    // Attributes
  private:
    std::vector<SpaceCell> SpaceCell_list;
    std::vector<StellarWay> StellarWay_list;
    // Setters and Getters
  };

};

#endif
