// Generated by dia2code
#ifndef STATE__POSITION__H
#define STATE__POSITION__H


namespace state {

  /// class Position - 
  class Position {
    // Attributes
  private:
    int X;
    int Y;
    // Operations
  public:
    Position ();
    int getX ();
    int getY ();
    int setX ();
    int setY ();
    // Setters and Getters
  };

};

#endif
