// Generated by dia2code
#ifndef STATE__RESSOURCE__H
#define STATE__RESSOURCE__H


namespace state {

  /// class Ressource - 
  class Ressource {
    // Attributes
  public:
    int production;
    int brume;
    int science;
    int food;
    // Operations
  public:
    int getTech ();
    int getBrume ();
    int getScience ();
    int getFood ();
    void setTech (int newTech);
    void setBrume (int newBrume);
    void setScience (int newScience);
    void setFood (int newFood);
    // Setters and Getters
  };

};

#endif
