// Generated by dia2code
#ifndef STATE__RESSOURCES__H
#define STATE__RESSOURCES__H


namespace state {

  enum Ressources {
    brume     = 1,
    food     = 2,
    science     = 3,
    production     = 4
  };

};

#endif
