// Generated by dia2code
#ifndef STATE__SHIP__H
#define STATE__SHIP__H


namespace state {
  class ShipStats;
  class Planet;
  class Objet;
}

#include "Ship_TypeID.h"
#include "ShipStats.h"
#include "Planet.h"
#include "Objet.h"

namespace state {

  /// class Ship - 
  class Ship : public state::Objet {
    // Attributes
  protected:
    Ship_TypeID type_ship;
    ShipStats ship_stats;
    int price;
    int production_cost;
    int level;
    int experience;
    // Operations
  public:
    Ship (Ship_TypeID ship);
    ~Ship ();
    void attack ();
    void moveShip ();
    void LevelUp ();
    void sell ();
    void advantage ();
    bool colonize (Planet planet);
    // Setters and Getters
    Ship_TypeID getType_ship() const;
    void setType_ship(Ship_TypeID type_ship);
    const ShipStats& getShip_stats() const;
    void setShip_stats(const ShipStats& ship_stats);
    int getPrice() const;
    void setPrice(int price);
    int getProduction_cost() const;
    void setProduction_cost(int production_cost);
    int getLevel() const;
    void setLevel(int level);
    int getExperience() const;
    void setExperience(int experience);
  };

};

#endif
