// Generated by dia2code
#ifndef STATE__SHIPSTATS__H
#define STATE__SHIPSTATS__H


namespace state {

  struct ShipStats {
    int health;
    int attack_point;
    int defense_point;
    int movement_point;
  };

};

#endif
