// Generated by dia2code
#ifndef STATE__SHIP_TYPEID__H
#define STATE__SHIP_TYPEID__H


namespace state {

  enum Ship_TypeID {
    CRUISER     = 0,
    DESTROYER     = 1,
    BATTLESHIP     = 2,
    COLON     = 3
  };

};

#endif
