// Generated by dia2code
#ifndef STATE__SPACECELL__H
#define STATE__SPACECELL__H


namespace state {
  class StellarSystem;
  class Objet;
  class Map;
}

#include "StellarSystem.h"
#include "Objet.h"
#include "Map.h"

namespace state {

  /// class SpaceCell - 
  class SpaceCell : public state::Objet {
    // Associations
    // Attributes
  private:
    bool isOccupied;
    StellarSystem system;
    // Setters and Getters
  };

};

#endif
