// Generated by dia2code
#ifndef STATE__STATUTID__H
#define STATE__STATUTID__H


namespace state {

  enum StatutID {
    colonizable     = 1,
    colonized     = 2,
    notColonizable     = 3
  };

};

#endif
