// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class Player;
  class Map;
}

#include "Player.h"
#include "Map.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  protected:
    Player player_a;
    Player player_b;
    int turn;
    // Operations
  public:
    State ();
    ~State ();
    void init ();
    void IncrementTurn ();
    // Setters and Getters
    const Player& getPlayer_a() const;
    void setPlayer_a(const Player& player_a);
    const Player& getPlayer_b() const;
    void setPlayer_b(const Player& player_b);
    int getTurn() const;
    void setTurn(int turn);
  };

};

#endif
