// Generated by dia2code
#ifndef STATE__STELLARWAY__H
#define STATE__STELLARWAY__H

#include <vector>

namespace state {
  class Map;
}

#include "Map.h"

namespace state {

  /// class StellarWay - 
  class StellarWay {
    // Associations
    // Attributes
  private:
    int length_way;
    int wayID;
    std::vector<std::pair<*StellarSytem,*StellarSystem>> system_ptr_list;
    // Operations
  public:
    int get_length ();
    str get_wayID ();
    // Setters and Getters
  };

};

#endif
