// Generated by dia2code
#ifndef STATE__TECHID__H
#define STATE__TECHID__H


namespace state {

  // enummeration
  /// class TechID - 
  class TechID {
    // Attributes
  public:
     a     = 1;
     b     = 2;
     c     = 3;
     d     = 4;
     e     = 5;
     f     = 6;
     g     = 7;
     h     = 8;
    // Setters and Getters
  };

};

#endif
