// Generated by dia2code
#ifndef STATE__TYPE_PLANETID__H
#define STATE__TYPE_PLANETID__H


namespace state {

  enum Type_planetID {
    cold     = 1,
    neutral     = 2,
    hot     = 3
  };

};

#endif
